<?php

namespace Polytech\Bundle\JMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionRepository extends EntityRepository
{
	public function findCurrentElections()
	{
		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM PolytechJMBundle:Election e WHERE e.started = true AND e.finished = false'
            );
        return $query->getResult();
	}

}
