<?php

namespace Polytech\Bundle\JMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
	public function countVotesByCandidatAndMention($candidatId, $mentionId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(v) FROM PolytechJMBundle:Vote v WHERE v.mention = :mention AND v.candidat = :candidat'
            );
        $query->setParameters(array(
            'mention' => $mentionId,
            'candidat' => $candidatId,
        ));
        return $query->getOneOrNullResult();
    }

    public function countVotesByCandidat($candidatId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(v) FROM PolytechJMBundle:Vote v WHERE v.candidat = :candidat'
            );
        $query->setParameters(array(
            'candidat' => $candidatId,
        ));
        return $query->getOneOrNullResult();
    }	
}
